#!/bin/sh

TOOLDIR="$(dirname "$0")"
REPO="${HOME}/.m2/repository"

java\
 -cp\
 ${REPO}/de/tototec/de.tototec.cmdoption/0.4.2/de.tototec.cmdoption-0.4.2.jar:\
${REPO}/com/typesafe/config/1.3.0/config-1.3.0.jar:\
${REPO}/org/scala-lang/scala-library/2.11.6/scala-library-2.11.6.jar:\
${TOOLDIR}/target/classes_2.11/\
 fscleaner.FsCleaner\
 "$@"
